"""Generate Railway's single-repository build without changing local Docker builds."""

from pathlib import Path
import re


TOOLKIT_REPOSITORY = "https://github.com/jjohnson5253/ldraw-nova.git"
TOOLKIT_REVISION = "98eac806bf721d83c9a04d31299050cea8d6d4f9"
INTEGRATION_REPOSITORY = "https://github.com/for-real-labs/brickbuilder-ai.git"
INTEGRATION_REVISION = "ae45ad73b946be1ffa301ffebd26e5bab939a084"


def source_stage(name: str, repository: str, revision: str) -> str:
    if not re.fullmatch(r"[a-f0-9]{40}", revision):
        raise ValueError("Build sources must use a complete immutable commit SHA")
    if not re.fullmatch(r"https://github.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+\.git", repository):
        raise ValueError("Build sources must use a GitHub HTTPS repository URL")
    return (
        f"FROM alpine:3.22 AS {name}\n"
        f"RUN apk add --no-cache git && git init /source && cd /source && "
        f"git remote add origin {repository} && git fetch --depth 1 origin {revision} "
        "&& git checkout --detach FETCH_HEAD\n"
    )


def railway_dockerfile(upstream: str) -> str:
    recipe = []
    for line in upstream.splitlines():
        if line.startswith("VOLUME "):
            recipe.append("# Persistent storage is supplied by the Railway /data volume.")
        elif line.startswith("COPY --from=nova "):
            if line.endswith("\\") or "[" in line:
                raise ValueError("Review the upstream toolkit COPY syntax before deploying")
            arguments = line.split()
            sources = " ".join("/source/" + value for value in arguments[2:-1])
            recipe.append(f"COPY --from=nova {sources} {arguments[-1]}")
        else:
            recipe.append(line)
    return (
        "# Generated by scripts/prepare_railway.py.\n"
        "# Toolkit pin follows ldraw-nova's main-BrickBuilderAI release.\n"
        + source_stage("nova", TOOLKIT_REPOSITORY, TOOLKIT_REVISION)
        + "\n"
        + source_stage("brickbuilder", INTEGRATION_REPOSITORY, INTEGRATION_REVISION)
        + "\n"
        + "\n".join(recipe)
        + "\n\n"
        + "COPY --from=brickbuilder /source/backend/nova-service/*.py /app/web/backend/brickbuilder_integration/\n"
        + "COPY --from=brickbuilder /source/backend/src/utils/generation_budget.py /app/web/backend/brickbuilder_integration/generation_budget.py\n"
        + "ARG RAILWAY_GIT_COMMIT_SHA\n"
        + "ARG NOVA_WEB_REVISION\n"
        + "RUN NOVA_BUILD_WEB_REVISION=${RAILWAY_GIT_COMMIT_SHA:-$NOVA_WEB_REVISION} "
        + "python3 -c \"import json, os, pathlib, re; "
        + "web = os.environ['NOVA_BUILD_WEB_REVISION']; "
        + "assert re.fullmatch('[a-f0-9]{40}', web), 'Set NOVA_WEB_REVISION for local builds'; "
        + "pathlib.Path('/app/web/backend/brickbuilder_integration/versions.json').write_text(json.dumps("
        + f"{{'toolkit': '{TOOLKIT_REVISION}', 'web': web}}))\" "
        + "&& chmod -R a-w /opt/ldraw-nova/ldraw_tools\n"
        + 'CMD ["sh", "-c", "exec uvicorn brickbuilder_integration.gateway:app --app-dir /app/web/backend --host ${NOVA_BIND_HOST:-0.0.0.0} --port 8000"]\n'
    )


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    (root / "Railway.Dockerfile").write_text(railway_dockerfile((root / "Dockerfile").read_text()))
